name: Deploy to Azure

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    name: Deploy Application to Azure
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r library-managment-api/requirements.txt

      # Deploy to Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          slot-name: production
          publish-profile: ${{ secrets.AZURE_CLIENT_SECRET }}
